version: "3.9"
services:
  couch_admin:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      secrets:
        - npmrc
      tags:
        - 'drgosstoica/couch_admin:1.0.0'
    image: 'dragosstoica/couch_admin:1.0.0'
    healthcheck:
      test: ["CMD", "node", "hck.js"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s


secrets:
  npmrc:
    file: ./secrets.app
