name: euro-invoice

services:
  
  couch:
    image: 'couchdb:3.3.1'
    container_name: couch
    hostname: couch
    restart: always
    environment:
      - 'COUCHDB_USER=${COUCHDB_USER}'
      - 'COUCHDB_PASSWORD=${COUCHDB_PASSWORD}'
    ports:
      - '5984:5984'
    volumes:
      - './dbcouch/etc:/opt/couchdb/etc/local.d'
      - './dbcouch/data:/opt/couchdb/data'
      - './dbcouch/log:/opt/couchdb/var/log'
    networks:
      - eu_invoice
    healthcheck:
      test:
        - CMD
        - curl
        - '--fail'
        - 'http://localhost:5984/_up'
      start_period: 10s
      interval: 10s
      timeout: 10s
      retries: 3
  
  couch_admin:
    image: 'dragosstoica/couch_admin:1.0.0'
    build:
      context: couch_admin
      dockerfile: Dockerfile
      target: production
      secrets:
        - wrk_secrets
    container_name: couch_admin
    hostname: couch_admin
    restart: unless-stopped
    env_file: .env
    depends_on:
      couch:
        condition: service_healthy
    healthcheck:
      test:
        - CMD
        - node
        - hck.js
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - eu_invoice
  
  euinvoiceapp:
    image: 'dragosstoica/euinvoice:1.0.0'
    build:
      context: euinvoice_app
      dockerfile: Dockerfile
      target: production
      secrets:
        - app_secrets
    container_name: euinvoice
    hostname: euinvoice
    restart: unless-stopped
    env_file: .env
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      couch:
        condition: service_healthy
      couch_admin:
        condition: service_healthy
    healthcheck:
      test:
        - CMD
        - node
        - hck.js
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - eu_invoice
      - nginx-proxy

networks:
  eu_invoice:
    driver: bridge
    name: eu_invoice
  nginx-proxy:
    external: true


secrets:
  wrk_secrets:
    file: ./couch_admin/secrets.app
  app_secrets:
    file: ./euinvoice_app/secrets.app
