version: "3.9"
services:
  euinvoiceapp:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      secrets:
        - npmrc
      tags:
        - 'dragosstoica/euinvoice:1.0.0'
    image: 'dragosstoica/euinvoice:1.0.0'
    ports:
      - ${APP_PORT}:${APP_PORT}
    healthcheck:
      test: ["CMD", "node", "hck.js"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 10s


secrets:
  npmrc:
    file: ./secrets.app
